server:
  port: 80

spring:
  profiles:
    active: ca
  application:
    name: BertMusic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: false
  flyway:
    enabled: true