

server:
  port: 80

spring:
  profiles:
    active: dev
  application:
    name: BertMusic
  datasource:
    driver-class-name:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}