CREATE TABLE TS_USER_ROLE
(
    RID          VARCHAR(32) NOT NULL COMMENT '数据主键',
    USER_ID      VARCHAR(32) COMMENT '用户ID',
    ROLE_ID      VARCHAR(32) COMMENT '角色ID',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME(6) COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    DELETED_BY   VARCHAR(32) COMMENT '删除人',
    DELETED_TIME DATETIME(6) COMMENT '删除时间',
    UPDATED_TIME DATETIME(6) COMMENT '更新时间',
    IF_DELETE    tinyint(1) COMMENT '是否删除',
    PRIMARY KEY (RID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT '用户角色表';
