CREATE TABLE TS_ROLE
(
    RID          VARCHAR(32) NOT NULL COMMENT '数据主键',
    ROLE_CODE    VARCHAR(255) COMMENT '角色编码',
    ROLE_NAME    VARCHAR(255) COMMENT '角色名称',
    ROLE_DESC    VARCHAR(255) COMMENT '角色描述',
    CREATED_BY   VARCHAR(32) COMMENT '创建人',
    CREATED_TIME DATETIME(6) COMMENT '创建时间',
    UPDATED_BY   VARCHAR(32) COMMENT '更新人',
    DELETED_BY   VARCHAR(32) COMMENT '删除人',
    DELETED_TIME DATETIME(6) COMMENT '删除时间',
    UPDATED_TIME DATETIME(6) COMMENT '更新时间',
    IF_DELETE    tinyint(1) COMMENT '是否删除',
    PRIMARY KEY (RID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT '角色表';

CREATE UNIQUE INDEX idx_role_code ON TS_ROLE (ROLE_CODE);